<a href="https://colab.research.google.com/github/skyballengine/fc_deep_learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Yay, Pytorch!")


Yay, Pytorch!


00. PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Intro To Tensors

### Creating tensors

Pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get number of dimensions of tensor
scalar.ndim

0

In [ ]:
# Get tensor back as an integer
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])


In [ ]:
# Get vector dimensions
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [2, 3]])
MATRIX


tensor([[7, 8],
        [2, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]


tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([2, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[3, 6, 9],
                        [4, 5, 6],
                       [11, 45, 7]]])


In [ ]:
TENSOR

tensor([[[ 3,  6,  9],
         [ 4,  5,  6],
         [11, 45,  7]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[ 3,  6,  9],
        [ 4,  5,  6],
        [11, 45,  7]])

In [ ]:
own_tensor = torch.tensor([[[[4, 6, 7, 8],
                             [11, 12, 13, 14],
                             [1, 3, 5, 7],
                             [3, 6, 9, 12]]]])

In [ ]:
own_tensor.ndim


4

In [ ]:
own_tensor.shape


torch.Size([1, 1, 4, 4])

In [ ]:
own_tensor[0][0][1][1]

tensor(12)

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Process
Start with random numbers -> look at dta -> update random numbers -> look at data -> update random numbers


In [ ]:
# Create a random tensor of size or shape
random_tensor = torch.rand(3,4)
torch.rand(1).ndim, torch.tensor(12).ndim


(1, 0)

In [ ]:
random_tensor


tensor([[0.7335, 0.8632, 0.5793, 0.9212],
        [0.8006, 0.8026, 0.9103, 0.1089],
        [0.8041, 0.6861, 0.0389, 0.3651]])

In [ ]:
 random_tensor.ndim

2

In [ ]:
random_tensor_2 = torch.rand(1, 11, 11)
random_tensor_2

tensor([[[0.6202, 0.2331, 0.1531, 0.3097, 0.8168, 0.3570, 0.0229, 0.6027,
          0.1397, 0.0168, 0.0442],
         [0.8305, 0.0583, 0.8846, 0.4961, 0.5684, 0.3284, 0.9152, 0.0241,
          0.7353, 0.0775, 0.3585],
         [0.6707, 0.5085, 0.1458, 0.5527, 0.6321, 0.5321, 0.1542, 0.5072,
          0.7382, 0.2596, 0.3017],
         [0.3204, 0.1017, 0.5256, 0.3359, 0.5338, 0.7829, 0.3234, 0.0370,
          0.0260, 0.6056, 0.2819],
         [0.9754, 0.3602, 0.3466, 0.3111, 0.6254, 0.8344, 0.2024, 0.5808,
          0.7637, 0.8235, 0.2866],
         [0.6983, 0.1453, 0.3681, 0.9743, 0.2492, 0.8785, 0.6268, 0.4017,
          0.6072, 0.0490, 0.9140],
         [0.9460, 0.4646, 0.3579, 0.1100, 0.1744, 0.9401, 0.7686, 0.8023,
          0.4086, 0.7314, 0.3999],
         [0.2563, 0.6138, 0.6727, 0.5181, 0.9710, 0.0754, 0.7086, 0.4351,
          0.4926, 0.8302, 0.7723],
         [0.2728, 0.1854, 0.7146, 0.6139, 0.5751, 0.1176, 0.8220, 0.4715,
          0.6285, 0.8920, 0.5434],
         [0.2871, 0

In [ ]:
torch.rand(1)


tensor([0.5299])

In [ ]:
# Create a random tensor with dimilar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_tensor


tensor([[[4.3914e-01, 3.0905e-01, 4.1453e-01],
         [4.0222e-01, 4.0438e-01, 5.2629e-01],
         [2.3579e-01, 2.3149e-01, 1.4523e-01],
         ...,
         [8.7219e-01, 1.6694e-01, 1.1603e-01],
         [8.1194e-02, 1.5593e-01, 9.0167e-01],
         [8.8170e-01, 2.4089e-01, 4.6801e-01]],

        [[6.1532e-01, 8.8615e-01, 7.4910e-01],
         [7.4482e-01, 2.4861e-01, 1.3470e-02],
         [2.2990e-01, 8.0183e-01, 8.0387e-01],
         ...,
         [5.5333e-01, 9.7899e-01, 3.2436e-02],
         [4.6591e-01, 7.4685e-01, 8.0174e-04],
         [4.5716e-02, 8.0094e-01, 4.4788e-01]],

        [[6.6381e-01, 7.9502e-01, 2.8838e-01],
         [6.5823e-01, 7.0447e-01, 1.8758e-01],
         [9.9699e-01, 5.8450e-02, 1.4285e-01],
         ...,
         [5.4489e-01, 3.4004e-04, 9.0815e-01],
         [8.0832e-01, 4.9266e-02, 6.6798e-01],
         [4.3147e-01, 2.7277e-02, 6.0016e-01]],

        ...,

        [[6.4681e-01, 1.3089e-01, 5.7139e-01],
         [8.1539e-01, 3.2506e-01, 2.2149e-01]

In [ ]:
random_tensor_3 = torch.rand(1, 2, 3, 4)
random_tensor_3

tensor([[[[0.6463, 0.5753, 0.7386, 0.5982],
          [0.9159, 0.9102, 0.8480, 0.2607],
          [0.6812, 0.2883, 0.6651, 0.5210]],

         [[0.7512, 0.8666, 0.9335, 0.4119],
          [0.6476, 0.4670, 0.1672, 0.4928],
          [0.0395, 0.3383, 0.6187, 0.0057]]]])

In [ ]:
random_tensor_3.shape, random_tensor_3.ndim

(torch.Size([1, 2, 3, 4]), 4)

### Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(2, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

In [ ]:
### Creating a range of tensors and tensor-like
# Use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_hundred = torch.arange(start=1, end=100, step=13)
one_to_hundred

tensor([ 1, 14, 27, 40, 53, 66, 79, 92])

In [ ]:
# Creating tensors-like
one_to_hundred_zeros = torch.zeros_like(input=one_to_hundred)
one_to_hundred_zeros, one_to_hundred_zeros.ndim

(tensor([0, 0, 0, 0, 0, 0, 0, 0]), 1)

### Tensor Datatypes

## Note - Tensor datatypes is one of the 3 big errors that we'll run into with Pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16, etc.),
                               device=None, # default is cpu, can shift to GPU or TPU ,
                               requires_grad=False) # if Pytorch should track the gradients with the tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype


torch.float16

In [ ]:
float_16_tensor.type(torch.float32)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor_2 = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor_2.dtype

torch.float16

In [ ]:
integer_8_tensor = torch.tensor([1, 2, 3], dtype=torch.int8)
integer_8_tensor

tensor([1, 2, 3], dtype=torch.int8)

In [ ]:
integer_8_tensor * float_16_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)

In [ ]:
integer_8_tensor.ndim, float_16_tensor.ndim

(1, 1)

In [ ]:
integer_8_tensor, float_16_tensor

(tensor([1, 2, 3], dtype=torch.int8),
 tensor([3., 6., 9.], dtype=torch.float16))

In [ ]:
float_64_tensor = torch.tensor([2, 3, 4], dtype=torch.float64)
float_64_tensor

tensor([2., 3., 4.], dtype=torch.float64)

In [ ]:
integer_8_tensor * float_64_tensor

tensor([ 2.,  6., 12.], dtype=torch.float64)

## Getting information form tensors (tensor attributes)

1. Tensors not right datatype - use tensor.dtype
2. Tensors not right shape - use tensor.shape
3. Tensors not on the right device - use tensor.device


In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5385, 0.0572, 0.1708, 0.0348],
        [0.9919, 0.1111, 0.4548, 0.0654],
        [0.2948, 0.6853, 0.6485, 0.0279]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor is: {some_tensor.dtype}")
print(f"Shape of tensor is: {some_tensor.shape}")
print(f"Device of tensor is: {some_tensor.device}")

tensor([[0.5385, 0.0572, 0.1708, 0.0348],
        [0.9919, 0.1111, 0.4548, 0.0654],
        [0.2948, 0.6853, 0.6485, 0.0279]])
Datatype of tensor is: torch.float32
Shape of tensor is: torch.Size([3, 4])
Device of tensor is: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
*   Addition
*   Subtraction
*   Multiplication (element wise)
*   Division
*   Matrix Multiplication


  

In [ ]:
# Create a tensor and add 10 to it
add_tensor = torch.tensor([3, 4, 5])
print(add_tensor)
print(add_tensor + 10)

tensor([3, 4, 5])
tensor([13, 14, 15])


In [ ]:
# Multiply tensor by 5
mult_tensor = add_tensor
mult_tensor * 5

tensor([15, 20, 25])

In [ ]:
# Divide tensor
divide_tensor = add_tensor
print(divide_tensor.dtype)
divided_tensor = divide_tensor / 2
print(divided_tensor.dtype)

torch.int64
torch.float32


In [ ]:
# Try out Pytorch built-in functions
torch.mul(add_tensor, 11)

tensor([33, 44, 55])

### Matrix Multiplication
Two methods of multiplication in neural networks and deep learning

1. Element wise is scalar multiplication
2. Matrix Multiplication is dot product (heavy dot in mathematical notation)

There are two main rules thart performing matrix multiplication must satisfy:
1. The inner dimensions must match
*   (3, 2) * (2, 3) good
*   (3, 2) * (4, 2) shape error

2. The resulting matrix has the shape of the outer dimensions

*   (3, 2) * (2, 3) -> (3, 3)

In [ ]:
# Element wise multiplication
tensor = torch.tensor([3, 4, 5])
print(f"{tensor} * {tensor}")
tensor * tensor

tensor([3, 4, 5]) * tensor([3, 4, 5])


tensor([ 9, 16, 25])

In [ ]:
# Matrix multiplication
tensor_price = torch.tensor([[3, 4, 2]])
tensor_number = torch.tensor([[13, 9, 7, 15],
                        [8, 7, 4, 6],
                         [6, 4, 0, 3]])
product_tensor = torch.matmul(tensor_price, tensor_number)
product_tensor


tensor([[83, 63, 37, 75]])

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(50)
CPU times: user 1.62 ms, sys: 0 ns, total: 1.62 ms
Wall time: 1.82 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 172 µs, sys: 1.04 ms, total: 1.21 ms
Wall time: 1.22 ms


tensor(50)

 ### One of the most common errors in deep learning are shape errors


In [ ]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 3))

tensor([[1.4170, 0.8412, 1.3149],
        [0.7813, 0.4349, 0.5711],
        [1.7239, 1.3515, 1.0753]])

In [ ]:
torch.matmul(torch.rand(10, 12), torch.rand(12, 2)).shape

torch.Size([10, 2])

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
tensor_A.shape, tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix tensor shape issues, we can manipulate their shape using a **transpose**.

A **transpose** switches the axes or dimensions of a tensor.

In [ ]:
tensor_B, tensor_B .shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)


In [ ]:
# Create a new tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
x.min

<function Tensor.min>

In [ ]:
x.min()

tensor(0)

In [ ]:
# Find the max
x.max()

tensor(90)

In [ ]:
x.dtype

torch.int64

In [ ]:
# Find the mean - the torch.mean() or tensor.mean() functions need certain datatypes to work
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
# Find the sum
x.sum()

tensor(450)

## Finding the positional min and max

In [ ]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x[1] = 1

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x

tensor([ 0,  1, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x[1] = 10

In [ ]:
x[0] = 1

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing tensors



*   Reshaping - reshapes an input tensor to a defined shape
*   View - return a view of an input tensor with a certain shape, but maintain the same memory as the original tensor

*   Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
*   Squeeze - removes all `1` dimensions from a tensor


*   Unsqueeze - add a `1` dimension to a target tensor
*   Permute - return a view of the input with dimensions permuted (swapped) in a certain way







In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_reshaped_2 = x.reshape(3, 3)
x_reshaped_2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x because a view of a tensor points to the tensors memory location
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
z[:, 0] = 1
x, z

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [ ]:
# Stack tensors on top of each opther
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_vstacked = torch.vstack([x, x, x])
x_vstacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_hstacked = torch.hstack([x, x, x])
x_hstacked

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6,
        7, 8, 9])

In [ ]:
x_stacked_2 = torch.stack([x, x, x, x], dim=-2)
x_stacked_2

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
torch.squeeze(x_reshaped_2)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x_reshaped_2.ndim

2

In [ ]:
x_reshaped_2.shape

torch.Size([3, 3])

In [ ]:
squeeze_tensor = torch.rand([3, 2, 1])
squeeze_tensor.shape, squeeze_tensor



(torch.Size([3, 2, 1]),
 tensor([[[0.2475],
          [0.4171]],
 
         [[0.8847],
          [0.0025]],
 
         [[0.3507],
          [0.2428]]]))

In [ ]:
squeeze_tensor[0]

tensor([[0.2475],
        [0.4171]])

In [ ]:
squeeze_tensor[0][0]

tensor([0.2475])

In [ ]:
squeeze_tensor[0][0][0]

tensor(0.2475)

In [ ]:
# torch.squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

print(f"\nSqueezed previous tensor: {x_reshaped.squeeze()}")
print(f"Squeezed previous tensor shape: {x_reshaped.squeeze().shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous tensor shape: torch.Size([1, 9])

Squeezed previous tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Squeezed previous tensor shape: torch.Size([9])


In [ ]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_reshaped.squeeze()}")
print(f"Previous target shape: {x_reshaped.squeeze().shape}")

# Add an extra dimension with unsqueeze()
x_unsqueezed = x_reshaped.squeeze().unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor shape: {x_unsqueezed.shape}")

Previous target: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous target shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New tensor shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of the target tensor
t = torch.randn([3, 4, 5])

In [ ]:
t

tensor([[[-0.3892, -0.4043,  1.3937, -0.7008,  0.3752],
         [-0.1865, -0.0776, -0.3193,  1.0667, -0.7570],
         [-0.1368, -0.2640,  0.2072,  0.9838,  0.8607],
         [-0.1166,  0.0652, -0.7275,  0.2730,  1.4417]],

        [[ 0.6773, -0.8386, -0.7090, -2.0404,  0.1705],
         [ 0.3447,  0.5259,  0.4307, -0.7637,  0.9057],
         [ 1.0590,  0.3609,  1.4567, -1.7826, -0.7923],
         [ 0.8454,  1.0065,  0.7340,  0.1227, -1.2851]],

        [[-1.1356, -0.7987,  0.5595,  0.0853, -0.1892],
         [-0.4868, -1.6277,  1.4342,  0.5354, -0.8453],
         [ 0.9096,  0.3547,  0.9631,  0.0278,  0.6039],
         [ 0.4854,  0.7703, -1.4473, -0.1073, -0.6149]]])

In [ ]:
# Permute the original tensor to rearrange the axes
t_permuted = t.permute(2, 0, 1)
print(f"Original tensor:\n {t}")
print(f" Original shape:\n {t.shape}")
print(f"\nPermuted t:\n {t_permuted}")
print(f"Permuted t shape:\n {t_permuted.shape}")

Original tensor:
 tensor([[[-0.3892, -0.4043,  1.3937, -0.7008,  0.3752],
         [-0.1865, -0.0776, -0.3193,  1.0667, -0.7570],
         [-0.1368, -0.2640,  0.2072,  0.9838,  0.8607],
         [-0.1166,  0.0652, -0.7275,  0.2730,  1.4417]],

        [[ 0.6773, -0.8386, -0.7090, -2.0404,  0.1705],
         [ 0.3447,  0.5259,  0.4307, -0.7637,  0.9057],
         [ 1.0590,  0.3609,  1.4567, -1.7826, -0.7923],
         [ 0.8454,  1.0065,  0.7340,  0.1227, -1.2851]],

        [[-1.1356, -0.7987,  0.5595,  0.0853, -0.1892],
         [-0.4868, -1.6277,  1.4342,  0.5354, -0.8453],
         [ 0.9096,  0.3547,  0.9631,  0.0278,  0.6039],
         [ 0.4854,  0.7703, -1.4473, -0.1073, -0.6149]]])
 Original shape:
 torch.Size([3, 4, 5])

Permuted t:
 tensor([[[-0.3892, -0.1865, -0.1368, -0.1166],
         [ 0.6773,  0.3447,  1.0590,  0.8454],
         [-1.1356, -0.4868,  0.9096,  0.4854]],

        [[-0.4043, -0.0776, -0.2640,  0.0652],
         [-0.8386,  0.5259,  0.3609,  1.0065],
         [-0.

In [ ]:
index_1 = t[1, 1, 1]

In [ ]:
t[1, 1, 1] = 6543.00
t_permuted

tensor([[[-3.8924e-01, -1.8648e-01, -1.3683e-01, -1.1656e-01],
         [ 6.7733e-01,  3.4470e-01,  1.0590e+00,  8.4538e-01],
         [-1.1356e+00, -4.8681e-01,  9.0963e-01,  4.8537e-01]],

        [[-4.0431e-01, -7.7550e-02, -2.6397e-01,  6.5200e-02],
         [-8.3857e-01,  6.5430e+03,  3.6093e-01,  1.0065e+00],
         [-7.9870e-01, -1.6277e+00,  3.5472e-01,  7.7032e-01]],

        [[ 1.3937e+00, -3.1931e-01,  2.0722e-01, -7.2748e-01],
         [-7.0899e-01,  4.3065e-01,  1.4567e+00,  7.3404e-01],
         [ 5.5953e-01,  1.4342e+00,  9.6312e-01, -1.4473e+00]],

        [[-7.0079e-01,  1.0667e+00,  9.8375e-01,  2.7295e-01],
         [-2.0404e+00, -7.6365e-01, -1.7826e+00,  1.2267e-01],
         [ 8.5292e-02,  5.3539e-01,  2.7811e-02, -1.0727e-01]],

        [[ 3.7524e-01, -7.5704e-01,  8.6066e-01,  1.4417e+00],
         [ 1.7054e-01,  9.0574e-01, -7.9228e-01, -1.2851e+00],
         [-1.8921e-01, -8.4534e-01,  6.0393e-01, -6.1490e-01]]])

In [ ]:
t[1, 1, 1], t_permuted[1, 1, 1]

(tensor(6543.), tensor(6543.))

## Indexing (selecting data from tensors)
## Indexing with PyTorch is similar to indexing with NUmpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)

In [ ]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing on middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Indexing on most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# Remember if the most outer dimesion is 1, then the first index must always be 0
x[0][2][2]

tensor(9)

In [ ]:
# We can also use ":" to select "all" of a target dimension
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Get all of the 0tha dn 1st dimensions, but only the 1st of the 2nd (last dimension)
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension, but only the 1st index of the 1st and 2nd dimension
x[:, 1, 1].shape

torch.Size([1])

In [ ]:
x.shape

torch.Size([1, 3, 3])

In [ ]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9 and to return 3, 6, 9

In [ ]:
# Return 9
x[0, 2, 2]

tensor(9)

In [ ]:
# Return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

# PyTorch tensors and Numpy

Numpy is a popular scientific numerical computing library.
Because of this, PyTorch has functionality to interact with it.


*   Data in NumPy; if we want in a PyTorch tensor -> `torch.from_numpy(ndarray)`
*   PyTorch tensor -> NumPy -> torch.Tensor.numpy()



In [ ]:
# NumPy array to tensor
array = np.arange(1.0, 10.0)
array

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tensor = torch.from_numpy(array).type(torch.float32) # when converting from numpy -> pytorch, datatype willbe float64 because that is the default datatype of numpy
# we can convert the datatype to the defualt float 32 just by using the type conversion in PyTorch

tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
# Changing the value of an array does not change the vlaue of the tensor
array += 1
array

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# tensor to numpy array
np_arr = tensor.numpy()

In [ ]:
np_arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
# changing the tensor does what to numpy tensor
tensor = tensor + 1

In [ ]:
tensor, np_arr

(tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [ ]:
tensor -= 1

In [ ]:
tensor, np_arr

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [ ]:
tens = torch.ones(7)
numpy_tens = tens.numpy()
tens, numpy_tens


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change tensor to see if changes are reflected in numpy array
tensor = tensor + 1
tensor, numpy_tens


(tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = torch.arange(1, 10)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = tensor.numpy()
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor = tensor + 1

In [ ]:
tensor, arr

(tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

## Reproducibility (trying to take the random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is flavor the randomness

In [ ]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9692, 0.1096, 0.4265, 0.6094],
        [0.8017, 0.8118, 0.6717, 0.6675],
        [0.1636, 0.3019, 0.8993, 0.5101]])
tensor([[0.4650, 0.9192, 0.4376, 0.0459],
        [0.8023, 0.6860, 0.5788, 0.6374],
        [0.1176, 0.8211, 0.1522, 0.7051]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's look at random but reproducable tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [ ]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

In [ ]:
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility



*   https://pytorch.org/docs/stable/notes/randomness.html?highlight=reproducibility
*   https://en.wikipedia.org/wiki/Random_seed



## Running tensors and pytorch objects on GPUs (and making faster computations)

# GPUs = faster computation on numbers, thanks to CUDA + Nvidia hardware + PyTorch working behind the scenes.



### 1. Getting a GPU

1. Easiest - Use Google Colab for free GPU ( can also upgrade for better/faster performance)
2. Use your own GPU - setup and investment
3. Use cloud computing - GCP, AWS, etc.
4. Getting started on your own machine : https://pytorch.org/get-started/locally/

For 2, 3 PyTorch + GPU drivers (CUDA) takes some setup - guides

In [ ]:
!nvidia-smi

Mon Sep 11 17:43:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Check for GPU with PyTorch
import torch
torch.cuda.is_available()

True

Device Agnostic Code

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

Run on GPU if available, else run on CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and models on the GPU

The reason we want our tensors on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on cpu)
tensor = torch.tensor([1, 2, 3], device="cpu")

In [ ]:
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# MOve tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# IF tensor is on GPU, can't transform it to Numpy

In [ ]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu()

In [ ]:
tensor_on_cpu.device

device(type='cpu')

In [ ]:
tensor.to(device)

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# How to successfully transform tensor and convert to numpy array
tensor_on_cpu = tensor_on_gpu.cpu().numpy()

In [ ]:
tensor_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Exercises - Section 00

In [ ]:
# Create a random tensor with shape of (7, 7)
torch.tensor([7, 7]).shape

torch.Size([2])

In [ ]:
rand_tens = torch.rand(7, 7)

In [ ]:
rand_tens.shape

torch.Size([7, 7])

In [ ]:
rand_tens_2 = torch.rand(1, 7)

In [ ]:
result = torch.matmul(rand_tens, rand_tens_2.T)
result, result.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [ ]:
torch.manual_seed(0)
rand_tens = torch.rand(7, 7)
print(rand_tens)
rand_tens_2 = torch.rand(1, 7)
print(rand_tens_2)
torch.matmul(rand_tens, rand_tens_2.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
rand_tens = torch.rand(2, 3)
rand_tens_2 = torch.rand(2, 3)
print(rand_tens.to(device))
print(rand_tens_2.to(device))

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [ ]:
# Matrix multiplication
tens_result = torch.matmul(rand_tens, rand_tens_2.T)
tens_result, tens_result.device, tens_result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 device(type='cpu'),
 torch.Size([2, 2]))

In [ ]:
rand_tens.device


device(type='cpu')

In [ ]:
result = torch.matmul(rand_tens.to(device), rand_tens_2.T.to(device))

In [ ]:
result, result.device, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.Size([2, 2]))

In [ ]:
result.min(), result.max()

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [ ]:
result.argmin(), result.argmax()

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [ ]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
squeezed_tensor = tensor.squeeze()
print(f"First tensor:\n {tensor} {tensor.shape}")
print(f"Second tensor:\n {squeezed_tensor} {squeezed_tensor.shape}")

First tensor:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
Second tensor:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
